default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: diego
  password: password
  port: 5432
  host: spostgres

development:
  <<: *default
  database: helpy_development

test:
  <<: *default
  database: helpy_test

production:
  <<: *default
  database: helpy_production
